export const regex: Record<string, RegExp> = {
    regex_ability: /Ability: ([A-z- ]+[A-z])$/,
    regex_Item: /Item: ([(A-z- ]+[A-z)])$/,
    // 's match
    regex_stat_change : /(The opposing )*(.+)'s ([A-z !]+)/,
    regex_magic_bounce : /bounced the ([A-z -]+) back!/,
    regex_start_battle : /Battle started between (.+) and (.+)!/,
    regex_uturn : /(The opposing )*([A-z -']+[A-z]) went back to (.*)!/,
    regex_gems : /The ([A-z ]+) strengthened ([A-z- ]+)'s power!/,
    regex_eat : /(The opposing )*([A-z -']+[A-z]) (ate|used) its ([A-z ]+)!/,
    regex_restorehp : /restored HP using its ([A-z ]+)!/,
    regex_knock : /(The opposing )*(.+) knocked off (the opposing )*(.+)\'s (.+)!/,
    regex_sent_out : /(.+) sent out /,
    regex_lost_health : /\((The opposing )*(.+) lost ([0-9\.]+)% of its health!\)/,
    regex_lost_health2 : /\((The opposing )*(.+) lost /,
    regex_mega : /(The opposing )*([A-z-']+) has Mega Evolved into Mega ([A-z -]+)!/,
    regex_come_back : /(.+), come back!/,
    single_word_pm : /(The opposing )*([A-z-']+) (.+)/,

    double_word_pm : /(The opposing )*([A-z:\.]+ [A-z]+) (.+)/,
    bracket_single_word_pm : /\((The opposing )*([A-z-']+) (.+)\)/,
    bracket_double_word_pm : /\((The opposing )*([A-z:\.]+ [A-z]+) (.+)\)/,
    regex_max_guard : /\(Max Guard started on (the opposing) (.+)!\)/,
    regex_key_stone : /(The opposing )*(.+)'s (.+) is reacting to the Key Stone!/,
    regex_ability_act : /\[(The opposing )*([A-z -'\u4E00-\u9FA5]+[A-z\u4E00-\u9FA5])'s (.+)\]/,
    regex_move_no_effect : /\((The opposing )*([A-z -']+[A-z]) blocked the effect!\)/,
    regex_pointed_stones : /Pointed stones dug into (the opposing )*([A-z -']+[A-z])!/,
    regex_after_taunt : /(The opposing )*([A-z -']+[A-z]) can't use ([A-z- ]+) after the taunt!/,
    regex_obtained : /(The opposing )*([A-z -']+[A-z]) obtained one ([A-z- ]+)\./,
    regex_chn : /[\u4E00-\u9FA5]+/,
    regex_go : /Go! (.+)\(/,
    regex_item_pokemon : /The ([A-z]+ [A-z]+) weakened (the)* damage to ([A-z -']+[A-z])!/,
    regex_g6_mega : /(The opposing )*([A-z -']+[A-z])'s ([A-z]+) is reacting to (.+)'s Mega Bracelet!/,
    regex_dynamax : /(The opposing )*([A-z -']+[A-z])'s Dynamax!/,
    regex_disable : /(The opposing )*([A-z -']+[A-z])'s ([A-z -']+[A-z]) was disabled!/,
    regex_cannot_use : /(The opposing )*([A-z -']+[A-z]) can't use ([A-z -']+[A-z])!/,
    regex_trace : /(The opposing )*(.+) traced (the opposing )*(.+)\'s (.+)!/,
    regex_seconds_left : /(.+) has ([0-9]+) seconds left./,
    regex_timer_on : /Battle timer is ON: inactive players will automatically lose when time's up. \(requested by (.+)\)/,
    regex_reset_timer : /The timer can't be re-enabled so soon after disabling it \(([0-9]+) seconds remaining\)./,
    regex_team : /(.+)'s team:/,
    regex_future_sight : /(The opposing )*([A-z -']+[A-z]) foresaw an attack!/,
    regex_future_sight2 : /(The opposing )*([A-z -']+[A-z]) took the Future Sight attack!/,
    regex_hp_restored : /(The opposing )*([A-z -']+[A-z])'s HP was restored./,
    regex_type_change : /(The opposing )*([A-z -']+[A-z])'s type changed to ([A-z]+)!/,
    regex_hit_times : /The Pokemon was hit ([0-9]+) times!/,
    regex_joined : /(.+) joined/,
    regex_left : /(.+) left/,
    regex_room_expired : /The room "(.+)" does not exist.\n\nThe battle you're looking for has expired. Battles expire after 15 minutes of inactivity unless they're saved.\nIn the future, remember to click "Save replay" to save a replay permanently./,
    regex_battle : /(.+) wants to battle!/,
    regex_cancelled : /(.+) cancelled the challenge./,
    regex_waitingavailable : /Waiting for battles to become available(.+)/,
    regex_challengex : /Challenge (.+)?/,
    regex_wftcy : /Waiting for (.+) to challenge you./,
    regex_waiting : /Waiting for (.+)/,
    regex_accepted : /(.+) accepted the challenge, starting /,
    regex_forfeited : /(.+) forfeited/,
    regex_copyofuntitled : /Copy of Untitled (.+)/,
    regex_copyof : /Copy of (.+)/,
    regex_untitled : /Untitled (.+)/,
    regex_newteam : /New (.+) Team/,
    regex_users : /(.+) users/,
    regex_theopposingfainted : /The opposing ([A-z -]+) fainted!/,
    regex_fainted : /([A-z -]+) fainted!/,
    regex_theopposingleftover : /The opposing ([A-z -]+) restored a little HP using its Leftovers!/,
    regex_leftover : /([A-z -]+) restored a little HP using its Leftovers!/,
    regex_wish : /([A-z -]+)'s wish came true!/,
    regex_doestaffecttd : /It doesn't affect the opposing ([A-z -]+)/,
    regex_doestaffect : /It doesn't affect ([A-z -]+)/,
    regex_younoteams : /You have no (.+) teams/,
    regex_youdontha : /you don't have any (.+) teams/,
    regex_xteams : /(.+) teams/,
    regex_theinverted : /The opposing ([A-z -]+)'s stat changes were inverted!/,
    regex_inverted : /([A-z -]+)'s stat changes were inverted!/,

    regex_toattackrd : /The opposing ([A-z -]+)'s Attack rose drastically!/,
    regex_todefenserd : /The opposing ([A-z -]+)'s Defense rose drastically!/,
    regex_tospard : /The opposing ([A-z -]+)'s Sp. Atk rose drastically!/,
    regex_tospdrd : /The opposing ([A-z -]+)'s Sp. Def rose drastically!/,
    regex_tosperd : /The opposing ([A-z -]+)'s Speed rose drastically!/,
    regex_toevasivenessrd : /The opposing ([A-z -]+)'s evasiveness rose drastically!/,
    regex_toaccuracyrd : /The opposing ([A-z -]+)'s accuracy rose drastically!/,
    regex_attackrd : /([A-z -]+)'s Attack rose drastically!/,
    regex_defenserd : /([A-z -]+)'s Defense rose drastically!/,
    regex_spard : /([A-z -]+)'s Sp. Atk rose drastically!/,
    regex_spdrd : /([A-z -]+)'s Sp. Def rose drastically!/,
    regex_sperd : /([A-z -]+)'s Speed rose drastically!/,
    regex_evasivenessrd : /([A-z -]+)'s evasiveness rose drastically!/,
    regex_accuracyrd : /([A-z -]+)'s accuracy rose drastically!/,

    regex_toattackfs : /The opposing ([A-z -]+)'s Attack fell severely!/,
    regex_todefensefs : /The opposing ([A-z -]+)'s Defense fell severely!/,
    regex_tospafs : /The opposing ([A-z -]+)'s Sp. Atk fell severely!/,
    regex_tospdfs : /The opposing ([A-z -]+)'s Sp. Def fell severely!/,
    regex_tospefs : /The opposing ([A-z -]+)'s Speed fell severely!/,
    regex_toevasivenessfs : /The opposing ([A-z -]+)'s evasiveness fell severely!/,
    regex_toaccuracyfs : /The opposing ([A-z -]+)'s accuracy fell severely!/,
    regex_attackrfs : /([A-z -]+)'s Attack fell severely!/,
    regex_defensefs : /([A-z -]+)'s Defense fell severely!/,
    regex_spafs : /([A-z -]+)'s Sp. Atk fell severely!/,
    regex_spdfs : /([A-z -]+)'s Sp. Def fell severely!/,
    regex_spefs : /([A-z -]+)'s Speed fell severely!/,
    regex_evasivenessfs : /([A-z -]+)'s evasiveness fell severely!/,
    regex_accuracyfs : /([A-z -]+)'s accuracy fell severely!/,

    regex_toattackrosesharply : /The opposing ([A-z -]+)'s Attack rose sharply!/,
    regex_todefenserosesharply : /The opposing ([A-z -]+)'s Defense rose sharply!/,
    regex_tospatkrosesharply : /The opposing ([A-z -]+)'s Sp. Atk rose sharply!/,
    regex_tospdefrosesharply : /The opposing ([A-z -]+)'s Sp. Def rose sharply!/,
    regex_tospeedrosesharply : /The opposing ([A-z -]+)'s Speed rose sharply!/,
    regex_toevasivenessrosesharply : /The opposing ([A-z -]+)'s evasiveness rose sharply!/,
    regex_toaccuracyrosesharply : /The opposing ([A-z -]+)'s accuracy rose sharply!/,
    regex_toattackfellharshly : /The opposing ([A-z -]+)'s Attack fell harshly!/,
    regex_todefensefellharshly : /The opposing ([A-z -]+)'s Defense fell harshly!/,
    regex_tospatkfellharshly : /The opposing ([A-z -]+)'s Sp. Atk fell harshly!/,
    regex_tospdeffellharshly : /The opposing ([A-z -]+)'s Sp. Def fell harshly!/,
    regex_tospeedfellharshly : /The opposing ([A-z -]+)'s Speed fell harshly!/,
    regex_toevasivenessfellharshly : /The opposing ([A-z -]+)'s evasiveness fell harshly!/,
    regex_toaccuracyfellharshly : /The opposing ([A-z -]+)'s accuracy fell harshly!/,

    regex_attackrosesharply : /([A-z -]+)'s Attack rose sharply!/,
    regex_defenserosesharply : /([A-z -]+)'s Defense rose sharply!/,
    regex_spatkrosesharply : /([A-z -]+)'s Sp. Atk rose sharply!/,
    regex_spdefrosesharply : /([A-z -]+)'s Sp. Def rose sharply!/,
    regex_speedrosesharply : /([A-z -]+)'s Speed rose sharply!/,
    regex_evasivenessrosesharply : /([A-z -]+)'s evasiveness rose sharply!/,
    regex_accuracyrosesharply : /([A-z -]+)'s accuracy rose sharply!/,
    regex_attackfellharshly : /([A-z -]+)'s Attack fell harshly!/,
    regex_defensefellharshly : /([A-z -]+)'s Defense fell harshly!/,
    regex_spatkfellharshly : /([A-z -]+)'s Sp. Atk fell harshly!/,
    regex_spdeffellharshly : /([A-z -]+)'s Sp. Def fell harshly!/,
    regex_speedfellharshly : /([A-z -]+)'s Speed fell harshly!/,
    regex_evasivenessfellharshly : /([A-z -]+)'s evasiveness fell harshly!/,
    regex_accuracyfellharshly : /([A-z -]+)'s accuracy fell harshly!/,

    regex_toattackrose : /The opposing ([A-z -]+)'s Attack rose!/,
    regex_todefenserose : /The opposing ([A-z -]+)'s Defense rose!/,
    regex_tospatkrose : /The opposing ([A-z -]+)'s Sp. Atk rose!/,
    regex_tospdefrose : /The opposing ([A-z -]+)'s Sp. Def rose!/,
    regex_tospeedrose : /The opposing ([A-z -]+)'s Speed rose!/,
    regex_toevasivenessrose : /The opposing ([A-z -]+)'s evasiveness rose!/,
    regex_toaccuracyrose : /The opposing ([A-z -]+)'s accuracy rose!/,
    regex_toattackfell : /The opposing ([A-z -]+)'s Attack fell!/,
    regex_todefensefell : /The opposing ([A-z -]+)'s Defense fell!/,
    regex_tospatkfell : /The opposing ([A-z -]+)'s Sp. Atk fell!/,
    regex_tospdeffell : /The opposing ([A-z -]+)'s Sp. Def fell!/,
    regex_tospeedfell : /The opposing ([A-z -]+)'s Speed fell!/,
    regex_toevasivenessfell : /The opposing ([A-z -]+)'s evasiveness fell!/,
    regex_toaccuracyfell : /The opposing ([A-z -]+)'s accuracy fell!/,

    regex_attackrose : /([A-z -]+)'s Attack rose!/,
    regex_defenserose : /([A-z -]+)'s Defense rose!/,
    regex_spatkrose : /([A-z -]+)'s Sp. Atk rose!/,
    regex_spdefrose : /([A-z -]+)'s Sp. Def rose!/,
    regex_speedrose : /([A-z -]+)'s Speed rose!/,
    regex_evasivenessrose : /([A-z -]+)'s evasiveness rose!/,
    regex_accuracyrose : /([A-z -]+)'s accuracy rose!/,
    regex_attackfell : /([A-z -]+)'s Attack fell!/,
    regex_defensefell : /([A-z -]+)'s Defense fell!/,
    regex_spatkfell : /([A-z -]+)'s Sp. Atk fell!/,
    regex_spdeffell : /([A-z -]+)'s Sp. Def fell!/,
    regex_speedfell : /([A-z -]+)'s Speed fell!/,
    regex_evasivenessfell : /([A-z -]+)'s evasiveness fell!/,
    regex_accuracyfell : /([A-z -]+)'s accuracy fell!/,

    regex_toattackh : /The opposing ([A-z -]+)'s Attack won't go any higher!/,
    regex_todefnseh : /The opposing ([A-z -]+)'s Defense won't go any higher!/,
    regex_tospah : /The opposing ([A-z -]+)'s Sp. Atk won't go any higher!/,
    regex_tospdh : /The opposing ([A-z -]+)'s Sp. Def won't go any higher!/,
    regex_tospeh : /The opposing ([A-z -]+)'s Speed won't go any higher!/,
    regex_toevasivengessh : /The opposing ([A-z -]+)'s evasiveness won't go any higher!/,
    regex_toaccuracyh : /The opposing ([A-z -]+)'s accuracy won't go any higher!/,
    regex_attackh : /([A-z -]+)'s Attack won't go any higher!/,
    regex_defnseh : /([A-z -]+)'s Defense won't go any higher!/,
    regex_spah : /([A-z -]+)'s Sp. Atk won't go any higher!/,
    regex_spdh : /([A-z -]+)'s Sp. Def won't go any higher!/,
    regex_speh : /([A-z -]+)'s Speed won't go any higher!/,
    regex_evasivengessh : /([A-z -]+)'s evasiveness won't go any higher!/,
    regex_accuracyh : /([A-z -]+)'s accuracy won't go any higher!/,

    regex_rejectchallenge : /(.+) rejected the challenge./,
    regex_thesustookto : /The substitute took damage for the opposing ([A-z -]+)!/,
    regex_thesustook : /The substitute took damage for ([A-z -]+)!/,
    regex_tohbawi : /The opposing ([A-z -]+) has been afflicted with an infestation by ([A-z -]+)!/,
    regex_hbawi : /([A-z -]+) has been afflicted with an infestation by the opposing ([A-z -]+)!/,
    regex_toihb : /The opposing ([A-z -]+) is hurt by ([A-z -]+)!/,
    regex_ihb : /([A-z -]+) is hurt by ([A-z -]+)!/,
    regex_iseoto : /It's super effective on the opposing ([A-z -]+)!/,
    regex_iseo : /It's super effective on ([A-z -]+)!/,
    regex_isnveoto : /It's not very effective on the opposing ([A-z -]+)./,
    regex_isnveo : /It's not very effective on ([A-z -]+)./,
    regex_achoto : /A critical hit on the opposing ([A-z -]+)!/,
    regex_acho : /A critical hit on ([A-z -]+)!/,
    regex_setc : /(.+) Single Elimination Tournament created./,
    regex_willuse : /(.+) will use (.+)./,
    regex_willswitchin : /(.+) will switch in, replacing (.+)./,
    regex_youjoined : /You joined (.+)/,
    regex_uteamsvf : /Your team is valid for (.+)./,
    regex_Metronome : /Waggling a finger let it use ([A-z -]+)!/,
    regex_iatbabi : /([A-z -]+) is about to be attacked by its ([A-z -]+)!/,
    regex_toiatbabi : /The opposing ([A-z -]+) is about to be attacked by its ([A-z -]+)!/,
    regex_ctop : /([A-z -]+) corroded the opposing ([A-z -]+)'s ([A-z -]+)!/,
    regex_toctop : /The opposing ([A-z -]+) corroded ([A-z -]+)'s ([A-z -]+)!/,
    regex_biftato : /But it failed to affect the opposing ([A-z -]+)!/,
    regex_bifta : /But it failed to affect ([A-z -]+)!/,
    regex_toshpif : /The opposing ([A-z -]+)'s HP is full!/,
    regex_shpif : /([A-z -]+)'s HP is full!/,
    regex_tobiuiz : /The opposing ([A-z -]+) boosted its ([A-z -]+) using its Z-Power!/,
    regex_biuiz : /([A-z -]+) boosted its ([A-z -]+) using its Z-Power!/,
    regex_tobisdizp : /The opposing ([A-z -]+) boosted its Sp. Def using its Z-Power!/,
    regex_tobisaizp : /The opposing ([A-z -]+) boosted its Sp. Atk using its Z-Power!/,
    regex_bisdizp : /([A-z -]+) boosted its Sp. Def using its Z-Power!/,
    regex_bisaizp : /([A-z -]+) boosted its Sp. Atk using its Z-Power!/,
    regex_tobstct : /The opposing ([A-z -]+)'s type changed to ([A-z -]+)!/,
    regex_bstct : /([A-z -]+)'s type changed to ([A-z -]+)!/,
    regex_towhbisb : /The opposing ([A-z -]+) was hurt by its Sticky Barb!/,
    regex_whbisb : /([A-z -]+) was hurt by its Sticky Barb!/,
    regex_twpsrtosa : /The Weakness Policy sharply raised the opposing ([A-z -]+)'s Attack!/,
    regex_twpsrtossa : /The Weakness Policy sharply raised the opposing ([A-z -]+)'s Sp. Atk!/,
    regex_twpsrsa : /The Weakness Policy sharply raised ([A-z -]+)'s Attack!/,
    regex_twpsrssa : /The Weakness Policy sharply raised ([A-z -]+)'s Sp. Atk!/,
    regex_thwctfto : /The healing wish came true for the opposing ([A-z -]+)!/,
    regex_thwctf : /The healing wish came true for ([A-z -]+)!/,
    regex_psdito : /Pointed stones dug into the opposing (.+)!/,
    regex_psdi : /Pointed stones dug into (.+)!/,
    regex_sfwhrrm : /(.+)'s fervent wish has reached Rayquaza-Mega!/,
    regex_sfwhrtorm : /(.+)'s fervent wish has reached the opposing Rayquaza-Mega!/,
}
